### ISSUE TITLE
Items not resizing with entity [18.1.16]

### ISSUE THREAD

**Issue by MetalKnight56** [Epic-Fight/epicfight#1006]
So i've been testing a bit an it seems that for ome reason the sword that are held by vexes won't resize like they should, they just stay the default size. Here are some pictures showing how it is:
![image](https://user-images.githubusercontent.com/77132244/168513258-e7c6ea15-cf15-4156-987e-cf100495094b.png)
And how it should look like:
![image](https://user-images.githubusercontent.com/77132244/168513323-46d5fe51-a4a4-4bd5-a95e-0789d19ab1cc.png)

Forge version: 40.1.0, running on 1.18.2

**Comment by Woodgoldtwo** [comment]
Idk

**Comment by Yesssssman** [comment]
Fixed in 18.1.18
