### ISSUE TITLE
Crash when trying to disable wither animations [18.1.16]

### ISSUE THREAD

**Issue by MetalKnight56** [Epic-Fight/epicfight#1009]
So i've been making a datapack to disable all animations from epic fight mod and when summoning wither boss with the disable animations datapack it just crashes.

(https://mclo.gs/oladsum) - Latest.log
[noanimations.zip](https://github.com/Yesssssman/epicfightmod/files/8697056/noanimations.zip) - Noanimations datapack (if you want to check the code or anything)

Forge: 40.1.0
Minecraft: 1.18.2

**Comment by Yesssssman** [comment]
Fixed in 18.1.18
