### ISSUE TITLE
Can't use creeper preset in creeperlike entities

### ISSUE THREAD

**Issue by MetalKnight56** [Epic-Fight/epicfight#1066]
Sickened_creeper entity uses minecraft's default model but when using preset in entity patch datapack, can't summon or spawn entity via spawn egg.  **GAME DOES NOT CRASH ONLY DOENS'T LET ME SPAWN SICKENED_CREEPER**
Here's the .json code
![image](https://user-images.githubusercontent.com/77132244/175787920-4b418928-7834-4990-9914-79a3afc17a51.png)

Console gives error everytime i try to summon/spawn it
https://mclo.gs/d9fN43A - Here's the error
https://mclo.gs/s01hTNY - Here's the whole log (since game launch)

And this is how creeper looks: 
![image](https://user-images.githubusercontent.com/77132244/175788147-027ca92e-baa2-4dab-88cc-de72b1fcb1f6.png)

WITHERSTORMMOD: witherstormmod-1.18.2-2.0-beta3.jar
EFM VERSION: 18.1.20
FORGE: 40.1.0

**Comment by Yesssssman** [comment]
It's hard to explain, but it is actually not a creeper type entity even tho it is seemingly a creeper.

```
java.lang.ClassCastException: class nonamecrackers2.witherstormmod.common.entity.SickenedCreeperEntity cannot be cast to class net.minecraft.world.entity.monster.Creeper
```
