### ISSUE TITLE
For 3d armor glitches

### ISSUE THREAD

**Issue by Yesssssman** [Epic-Fight/epicfight#536]
![2021-09-07_20 30 59 (4)](https://user-images.githubusercontent.com/79469058/132344755-c32937ff-dbfd-4784-bee0-605ade83e74c.png)
![2021-09-07_20 30 59 (3)](https://user-images.githubusercontent.com/79469058/132344807-bea6a300-4e9d-435a-bd85-5185e06ccb95.png)
![2021-09-07_20 30 59 (5)](https://user-images.githubusercontent.com/79469058/132344868-4e4fb928-e7c7-49c3-8742-0ebefcd25330.png)

[Applied examples (Ice and fire, Botania, Thaumcraft)]

![2021-09-07_20 30 59 (2)](https://user-images.githubusercontent.com/79469058/132345048-ead077d8-585b-4dc1-a5ab-db2d0d520c4b.png)
![2021-09-07_20 30 59 (1)](https://user-images.githubusercontent.com/79469058/132345075-78b2bcc4-9c99-405f-b044-8d6af350ff35.png)

[Broken examples (Botania, Dungeons gear)]

There are lots of ways to render custom armor, but Epic Fight can create an autogeneration model in a restricted way. This is not a fault for mod makers. They don't necessarily have to make custom armor working in Epic Fight.

Nevertheless, If someone wants to make custom armor visible with Epic Fight animation, I'll be willing to give them a solution on how to modify their code. If he says he doesn't want to fix their code, Don't bother him anymore.

<details>
  <summary>Guideline</summary>

In the constructor of YourModel.class

```
this.bipedHead.addChild(your modelrenderer);
this.bipedRightArm.addChild(your modelrenderer);
this.bipedRightLeg.addChild(your modelrenderer);
this.bipedLeftLeg.addChild(your modelrenderer);
this.bipedBody.addChild(your modelrenderer);
this.bipedLeftArm.addChild(your modelrenderer);
```

Like the example above, make your ModelRenderer (or ModelPart in the official mapping) instance hierarchically. And recommend finishing all the transformation stuff in Constructor as possible, because my autogeneration mechanism is supposed to be executed without ModelRenderer#render method.

Cool example creating a fully compatible model.
[#](https://github.com/Alex-the-666/Ice_and_Fire/blob/1.16.3/src/main/java/com/github/alexthe666/iceandfire/client/model/ModelDragonsteelFireArmor.java) (Ice and Fire Dragonsteel armor model)

</details>

**Comment by Pfr19** [comment]
But, what i have to do?, where is the model? what i have to add.

**Comment by Yesssssman** [comment]
@Pfr19 Are you a mod developer? If so, I attached the guideline so refer to it.

**Comment by Ripticor** [comment]
but where do i find that. I am not a mod developer help pls

**Comment by MetalKnight56** [comment]
Patched Dungeon Gear mod here: https://www.planetminecraft.com/data-pack/epic-fight-dungeon-gear-patch/
