### ISSUE TITLE
Crossbow's charging animation continues when item dropped

### ISSUE THREAD

**Issue by MetalKnight56** [Epic-Fight/epicfight#995]
In this image i'm just holding a charged crossbow
![image](https://user-images.githubusercontent.com/77132244/167733153-7230ad41-c067-4e45-b571-328ece7f0193.png)
In this image, i've just dropped the crossbow, yet the animation that i'm holding it, still persists even after attacking, it will only dissapear once i hold another weapond
![image](https://user-images.githubusercontent.com/77132244/167733280-44c75887-6167-405f-84f9-da1d4662feef.png)
VERSION [18.1.14-alpha], forge [40.1.0]

**Comment by Yesssssman** [comment]
Fixed in 18.1.15
